### ISSUE TITLE
DraggableFooter | It should automatically open with an action, or a function

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#1146]
When I select a date range from calendar, the footer with options remains hidden unless I drag it up, but I want it to open about 40% when I select a date range.

**Comment by kmahmood74** [comment]
@snehmehta there is not documentation or kitchen sink for this. This is not right. We need to always update.

**Comment by kmahmood74** [comment]
re-opening it, please add kitchen sink and documentation

**Comment by snehmehta** [comment]
kitchen sink:
https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/rDSqDYVIW7wWhMKSpE3Q

**Comment by kmahmood74** [comment]
@snehmehta thanks 

1. can you please let the footer be draggable by the user, it seems to be draggable only by programmatically which is not the primary use case. Also please add a drag handle. 
2. Add a reference to it from one of the main pages otherwise it is unreachable
3. please add documentation as well
