### ISSUE TITLE
Ensemble Live in Web/Studio - top two tiles in kitchen sink app are not clickable

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1218]
1. login to the studio
2. go here - https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/nAvv0XLuq92N82qpKPCI
3. Pick any option like Form Widgets or Layout widgets
4. top two tiles are not clickable, rest work fine

Same issue when running kitchen sink separately in Ensemble Live on the web. I think this has been an issue for a while

cc @amin-nas @vusters

**Comment by vinothvino42** [comment]
This is fixed now. It is happening only when the build is built with HTML renderer, its working fine with Canvaskit renderer

 It's an issue caused by the Lottie widget for the web, the HTMLElementView widget is used for it which is not allowing other views to receive the mouse scroll event. 

It can be fixed with a package (https://pub.dev/packages/pointer_interceptor). Already we have a style property called `captureWebPointer` boolean property for the widgets. Now I added it for the page styles too, here's the PR for it - https://github.com/EnsembleUI/ensemble/pull/1238

**Comment by kmahmood74** [comment]
@vinothvino42 why are you marking it as released when the PR is still open? This is not released

**Comment by kmahmood74** [comment]
@vinothvino42 your explanation is hard to understand. 

1. Why did this just start happening when Lottie has been there for at least a year if not more for html renderer?
2. why is it just blocking the top two tiles?
3. there is no lottie on those pages?

We can't fix a new regression by adding another flutter package. You have to investigate the issue properly. We can't put band-aids like this. 

cc @snehmehta

**Comment by vinothvino42** [comment]
> @vinothvino42 your explanation is hard to understand.
> 
> 1. Why did this just start happening when Lottie has been there for at least a year if not more for html renderer?
> 2. why is it just blocking the top two tiles?
> 3. there is no lottie on those pages?
> 
> We can't fix a new regression by adding another flutter package. You have to investigate the issue properly. We can't put band-aids like this.
> 
> cc @snehmehta

@kmahmood74 First I need to tell you that I didn't implemented this package, we're already having it https://github.com/EnsembleUI/ensemble/blob/1978c082248a2a017756317a4eaa523ced386a92/pubspec.yaml#L98
and we've setter property for it in the widget controller https://github.com/EnsembleUI/ensemble/blob/1978c082248a2a017756317a4eaa523ced386a92/lib/widget/helpers/controllers.dart#L137



**Answers to your questions**

1. Not sure how it worked before, maybe because of canvaskit being used, not sure. The issue is with HTMLElementView which is used now for the Lottie widget if it's HTML Renderer and Web. See here - https://github.com/EnsembleUI/ensemble/blob/1978c082248a2a017756317a4eaa523ced386a92/lib/widget/lottie/web/lottiestate.dart#L71
2. I tried setting the background color to the lottie widget and tested it navigating to next page, the next page is not receiving the mouse scroll events only for this background lottie widget area. Its working if I scroll or click any other places (ex: in the content widget page or form widget page in ensemble kitchen sink app) 
3. It's in the previous page that absorbs the click or scroll events which is happening in the next page (ex: the content widget page)

See this issues
https://github.com/flutter/flutter/issues/86021

Now I simply added the `captureWebPointer` style property for the custom widgets that we've in the Ensemble Kitchen Sink Live app widgets section, so now it'll receive the mouse scroll or click events to those widgets. I checked it in Kitchen Sink Ensemble Live and now it's working fine, that's why I marked this issue as `Released`.

I added the `captureWebPointer` support for the page styles too, that's what this PR is https://github.com/EnsembleUI/ensemble/pull/1238

**Comment by kmahmood74** [comment]
@vinothvino42 we can't just ask people to add captureWebPointer: true on all their widgets. That's not right. We need to fix this properly. Also remove this property from all custom widgets in Kitchen Sink after you have a proper fix. 

cc @vusters

**Comment by vinothvino42** [comment]
@kmahmood74 @vusters New PR - #1240

**Comment by kmahmood74** [comment]
@vinothvino42 get into the habit of closing the tickets once they are complete
