### ISSUE TITLE
Require Splash Feedback Speed Control for Container Widgets

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble#1596]
[https://github.com/EnsembleUI/ensemble/issues/1546
](url)
Require Enhancements on this Ticket.

New Requirements:
- Require Additional Speed Control Property on Splash Feedback
- Proposed speed unit is Milliseconds.

**Comment by vusters** [comment]
Commtited https://github.com/EnsembleUI/ensemble/commit/944dd2f94c5276babafcf3573631e4a203fe8343. Studio and Ensemble Go has also been updated (Android coming soon).

Studio's typeaheads also explain the new usage but here's the summary of the newly added styles:
- `splashDuration` - The duration in ms when tap and release on the widget. This is the duration it takes to fill the widget's surface with the splashColor.
- `splashFadeDuration` - The duration it takes to fade out once tapped. Since a typical tap starts and ends immdiately, this splashFadeDuration executes almost at the same time as the splashDuration, so ideally it should be equal or longer than splashDuration to see the entire effect.
- `unconfirmedSplashDuration` - This happens when the user tap and hold (not yet released). It is called unconfirmed since the tap will be cancelled if the user moves out of the tap area and release. Usually this should be longer (around 1 secs) to signify that the user has not confirmed the tap.

The combination of these 3 should give more flexibility to control the animation.
