### ISSUE TITLE
Make device_preview work with Flutter 3.10.0

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#500]
Device_Preview clicking area is off with the latest upgrade to Flutter 3.10.0. I had to disable it. Please fix and re-enable.

**Comment by kmahmood74** [comment]
@vinothvino42 this is urgent as device preview is broken right now

**Comment by amin-nas** [comment]
@vusters buttons' onTap are not working when the device preview is on. Whatever you disabled has not resolved the issue.

**Comment by vinothvino42** [comment]
> @vinothvino42 this is urgent as device preview is broken right now

@kmahmood74 @vusters I found the issue it's because of `SelectionArea` widget is not working properly in this version of Flutter. We're returning our Screen widget with SelectionArea as the root widget, this causes the issue. I just temporarily removed it and updated it in this PR #504 

Now try it with an `ensemble-live` app like this below
1. First change the ensemble git package ref to `flutter-migration` branch in the `pubspec.yaml `
2. Enable the DevicePreview in the `App.dart`
